import type { IconType } from 'react-icons'
import {
  FaBaby,
  FaBabyCarriage,
  FaBath,
  FaBed,
  FaBell,
  FaBicycle,
  FaBirthdayCake,
  FaBolt,
  FaBook,
  FaBriefcase,
  FaBroom,
  FaBrush,
  FaBuilding,
  FaBullhorn,
  FaBus,
  FaCamera,
  FaCar,
  FaCarSide,
  FaChalkboardTeacher,
  FaChargingStation,
  FaChild,
  FaClipboardList,
  FaClock,
  FaCloud,
  FaCoffee,
  FaCog,
  FaCogs,
  FaCoins,
  FaComments,
  FaCouch,
  FaCut,
  FaDolly,
  FaDoorOpen,
  FaDumbbell,
  FaEnvelope,
  FaFan,
  FaFileAlt,
  FaFillDrip,
  FaFireExtinguisher,
  FaFirstAid,
  FaFootballBall,
  FaGamepad,
  FaGavel,
  FaGift,
  FaHammer,
  FaHandsHelping,
  FaHardHat,
  FaHeadset,
  FaHeart,
  FaHelicopter,
  FaHiking,
  FaHome,
  FaHorse,
  FaHotTub,
  FaHotel,
  FaIceCream,
  FaIcons,
  FaImage,
  FaKey,
  FaLaptop,
  FaLeaf,
  FaLightbulb,
  FaLock,
  FaMapMarkedAlt,
  FaMicrophone,
  FaMobileAlt,
  FaMotorcycle,
  FaMusic,
  FaPaintRoller,
  FaPalette,
  FaPaw,
  FaPen,
  FaPencilRuler,
  FaPercentage,
  FaPhone,
  FaPiggyBank,
  FaPills,
  FaPlane,
  FaPlug,
  FaPlusCircle,
  FaPodcast,
  FaPumpSoap,
  FaPuzzlePiece,
  FaReceipt,
  FaRing,
  FaRoad,
  FaRobot,
  FaRocket,
  FaRoute,
  FaRunning,
  FaSatelliteDish,
  FaSchool,
  FaScrewdriver,
  FaSeedling,
  FaShapes,
  FaShieldAlt,
  FaShippingFast,
  FaShoePrints,
  FaShoppingBag,
  FaShoppingBasket,
  FaShoppingCart,
  FaShower,
  FaSitemap,
  FaSkiing,
  FaSkull,
  FaSmile,
  FaSoap,
  FaSpa,
  FaSprayCan,
  FaStar,
  FaStore,
  FaSuitcase,
  FaSuitcaseRolling,
  FaSwimmingPool,
  FaSyringe,
  FaTableTennis,
  FaTabletAlt,
  FaTags,
  FaTaxi,
  FaTeeth,
  FaThLarge,
  FaThermometerHalf,
  FaTint,
  FaToggleOn,
  FaToolbox,
  FaTools,
  FaTooth,
  FaTractor,
  FaTrain,
  FaTree,
  FaTrophy,
  FaTruck,
  FaTshirt,
  FaUmbrellaBeach,
  FaUniversity,
  FaUtensils,
  FaVideo,
  FaWalking,
  FaWarehouse,
  FaWeight,
  FaWifi,
  FaWineBottle,
  FaWrench,
} from 'react-icons/fa'

export type CategoryFa5Entry = {
  /** Font Awesome 5 glyph name for Expo `FontAwesome5` (`name` prop). */
  key: string
  /** Human label for search and tooltips. */
  label: string
  Icon: IconType
}

export const CATEGORY_FA5_ICONS: CategoryFa5Entry[] = [
  { key: 'baby', label: 'Baby', Icon: FaBaby },
  { key: 'baby-carriage', label: 'Baby carriage', Icon: FaBabyCarriage },
  { key: 'bath', label: 'Bath', Icon: FaBath },
  { key: 'bed', label: 'Bed', Icon: FaBed },
  { key: 'bell', label: 'Bell', Icon: FaBell },
  { key: 'bicycle', label: 'Bicycle', Icon: FaBicycle },
  { key: 'birthday-cake', label: 'Birthday cake', Icon: FaBirthdayCake },
  { key: 'bolt', label: 'Bolt', Icon: FaBolt },
  { key: 'book', label: 'Book', Icon: FaBook },
  { key: 'briefcase', label: 'Briefcase', Icon: FaBriefcase },
  { key: 'broom', label: 'Broom', Icon: FaBroom },
  { key: 'brush', label: 'Brush', Icon: FaBrush },
  { key: 'building', label: 'Building', Icon: FaBuilding },
  { key: 'bullhorn', label: 'Bullhorn', Icon: FaBullhorn },
  { key: 'bus', label: 'Bus', Icon: FaBus },
  { key: 'camera', label: 'Camera', Icon: FaCamera },
  { key: 'car', label: 'Car', Icon: FaCar },
  { key: 'car-side', label: 'Car side', Icon: FaCarSide },
  { key: 'chalkboard-teacher', label: 'Teaching', Icon: FaChalkboardTeacher },
  { key: 'charging-station', label: 'Charging station', Icon: FaChargingStation },
  { key: 'child', label: 'Child', Icon: FaChild },
  { key: 'clipboard-list', label: 'Clipboard list', Icon: FaClipboardList },
  { key: 'clock', label: 'Clock', Icon: FaClock },
  { key: 'cloud', label: 'Cloud', Icon: FaCloud },
  { key: 'coffee', label: 'Coffee', Icon: FaCoffee },
  { key: 'cog', label: 'Cog', Icon: FaCog },
  { key: 'cogs', label: 'Cogs', Icon: FaCogs },
  { key: 'coins', label: 'Coins', Icon: FaCoins },
  { key: 'comments', label: 'Comments', Icon: FaComments },
  { key: 'couch', label: 'Couch', Icon: FaCouch },
  { key: 'cut', label: 'Cut / scissors', Icon: FaCut },
  { key: 'dolly', label: 'Dolly', Icon: FaDolly },
  { key: 'door-open', label: 'Door open', Icon: FaDoorOpen },
  { key: 'dumbbell', label: 'Dumbbell', Icon: FaDumbbell },
  { key: 'envelope', label: 'Envelope', Icon: FaEnvelope },
  { key: 'fan', label: 'Fan', Icon: FaFan },
  { key: 'file-alt', label: 'Document', Icon: FaFileAlt },
  { key: 'fill-drip', label: 'Paint', Icon: FaFillDrip },
  { key: 'fire-extinguisher', label: 'Fire extinguisher', Icon: FaFireExtinguisher },
  { key: 'first-aid', label: 'First aid', Icon: FaFirstAid },
  { key: 'football-ball', label: 'Football', Icon: FaFootballBall },
  { key: 'gamepad', label: 'Gamepad', Icon: FaGamepad },
  { key: 'gavel', label: 'Gavel', Icon: FaGavel },
  { key: 'gift', label: 'Gift', Icon: FaGift },
  { key: 'hammer', label: 'Hammer', Icon: FaHammer },
  { key: 'hands-helping', label: 'Hands helping', Icon: FaHandsHelping },
  { key: 'hard-hat', label: 'Hard hat', Icon: FaHardHat },
  { key: 'headset', label: 'Headset', Icon: FaHeadset },
  { key: 'heart', label: 'Heart', Icon: FaHeart },
  { key: 'helicopter', label: 'Helicopter', Icon: FaHelicopter },
  { key: 'hiking', label: 'Hiking', Icon: FaHiking },
  { key: 'home', label: 'Home', Icon: FaHome },
  { key: 'horse', label: 'Horse', Icon: FaHorse },
  { key: 'hot-tub', label: 'Hot tub', Icon: FaHotTub },
  { key: 'hotel', label: 'Hotel', Icon: FaHotel },
  { key: 'ice-cream', label: 'Ice cream', Icon: FaIceCream },
  { key: 'icons', label: 'Icons', Icon: FaIcons },
  { key: 'image', label: 'Image', Icon: FaImage },
  { key: 'key', label: 'Key', Icon: FaKey },
  { key: 'laptop', label: 'Laptop', Icon: FaLaptop },
  { key: 'leaf', label: 'Leaf / eco', Icon: FaLeaf },
  { key: 'lightbulb', label: 'Lightbulb', Icon: FaLightbulb },
  { key: 'lock', label: 'Lock', Icon: FaLock },
  { key: 'map-marked-alt', label: 'Map', Icon: FaMapMarkedAlt },
  { key: 'microphone', label: 'Microphone', Icon: FaMicrophone },
  { key: 'mobile-alt', label: 'Mobile phone', Icon: FaMobileAlt },
  { key: 'motorcycle', label: 'Motorcycle', Icon: FaMotorcycle },
  { key: 'music', label: 'Music', Icon: FaMusic },
  { key: 'paint-roller', label: 'Paint roller', Icon: FaPaintRoller },
  { key: 'palette', label: 'Palette', Icon: FaPalette },
  { key: 'paw', label: 'Paw', Icon: FaPaw },
  { key: 'pen', label: 'Pen', Icon: FaPen },
  { key: 'pencil-ruler', label: 'Pencil ruler', Icon: FaPencilRuler },
  { key: 'percentage', label: 'Percentage', Icon: FaPercentage },
  { key: 'phone', label: 'Phone', Icon: FaPhone },
  { key: 'piggy-bank', label: 'Piggy bank', Icon: FaPiggyBank },
  { key: 'pills', label: 'Pills', Icon: FaPills },
  { key: 'plane', label: 'Plane', Icon: FaPlane },
  { key: 'plug', label: 'Plug', Icon: FaPlug },
  { key: 'plus-circle', label: 'Plus circle', Icon: FaPlusCircle },
  { key: 'podcast', label: 'Podcast', Icon: FaPodcast },
  { key: 'pump-soap', label: 'Pump soap', Icon: FaPumpSoap },
  { key: 'puzzle-piece', label: 'Puzzle', Icon: FaPuzzlePiece },
  { key: 'receipt', label: 'Receipt', Icon: FaReceipt },
  { key: 'ring', label: 'Ring', Icon: FaRing },
  { key: 'road', label: 'Road', Icon: FaRoad },
  { key: 'robot', label: 'Robot', Icon: FaRobot },
  { key: 'rocket', label: 'Rocket', Icon: FaRocket },
  { key: 'route', label: 'Route', Icon: FaRoute },
  { key: 'running', label: 'Running', Icon: FaRunning },
  { key: 'satellite-dish', label: 'Satellite', Icon: FaSatelliteDish },
  { key: 'school', label: 'School', Icon: FaSchool },
  { key: 'screwdriver', label: 'Screwdriver', Icon: FaScrewdriver },
  { key: 'seedling', label: 'Seedling', Icon: FaSeedling },
  { key: 'shapes', label: 'Shapes', Icon: FaShapes },
  { key: 'shield-alt', label: 'Shield', Icon: FaShieldAlt },
  { key: 'shipping-fast', label: 'Shipping fast', Icon: FaShippingFast },
  { key: 'shoe-prints', label: 'Shoe prints', Icon: FaShoePrints },
  { key: 'shopping-bag', label: 'Shopping bag', Icon: FaShoppingBag },
  { key: 'shopping-basket', label: 'Shopping basket', Icon: FaShoppingBasket },
  { key: 'shopping-cart', label: 'Shopping cart', Icon: FaShoppingCart },
  { key: 'shower', label: 'Shower', Icon: FaShower },
  { key: 'sitemap', label: 'Sitemap', Icon: FaSitemap },
  { key: 'skiing', label: 'Skiing', Icon: FaSkiing },
  { key: 'skull', label: 'Skull', Icon: FaSkull },
  { key: 'smile', label: 'Smile', Icon: FaSmile },
  { key: 'soap', label: 'Soap', Icon: FaSoap },
  { key: 'spa', label: 'Spa', Icon: FaSpa },
  { key: 'spray-can', label: 'Spray can', Icon: FaSprayCan },
  { key: 'star', label: 'Star', Icon: FaStar },
  { key: 'store', label: 'Store', Icon: FaStore },
  { key: 'suitcase', label: 'Suitcase', Icon: FaSuitcase },
  { key: 'suitcase-rolling', label: 'Luggage', Icon: FaSuitcaseRolling },
  { key: 'swimming-pool', label: 'Swimming pool', Icon: FaSwimmingPool },
  { key: 'syringe', label: 'Syringe', Icon: FaSyringe },
  { key: 'table-tennis', label: 'Table tennis', Icon: FaTableTennis },
  { key: 'tablet-alt', label: 'Tablet', Icon: FaTabletAlt },
  { key: 'tags', label: 'Tags', Icon: FaTags },
  { key: 'taxi', label: 'Taxi', Icon: FaTaxi },
  { key: 'teeth', label: 'Teeth / dental', Icon: FaTeeth },
  { key: 'th-large', label: 'Grid', Icon: FaThLarge },
  { key: 'thermometer-half', label: 'Thermometer', Icon: FaThermometerHalf },
  { key: 'tint', label: 'Tint / water', Icon: FaTint },
  { key: 'toggle-on', label: 'Toggle', Icon: FaToggleOn },
  { key: 'toolbox', label: 'Toolbox', Icon: FaToolbox },
  { key: 'tools', label: 'Tools', Icon: FaTools },
  { key: 'tooth', label: 'Tooth', Icon: FaTooth },
  { key: 'tractor', label: 'Tractor', Icon: FaTractor },
  { key: 'train', label: 'Train', Icon: FaTrain },
  { key: 'tree', label: 'Tree', Icon: FaTree },
  { key: 'trophy', label: 'Trophy', Icon: FaTrophy },
  { key: 'truck', label: 'Truck', Icon: FaTruck },
  { key: 'tshirt', label: 'T-shirt', Icon: FaTshirt },
  { key: 'umbrella-beach', label: 'Beach', Icon: FaUmbrellaBeach },
  { key: 'university', label: 'University', Icon: FaUniversity },
  { key: 'utensils', label: 'Utensils / food', Icon: FaUtensils },
  { key: 'video', label: 'Video', Icon: FaVideo },
  { key: 'walking', label: 'Walking', Icon: FaWalking },
  { key: 'warehouse', label: 'Warehouse', Icon: FaWarehouse },
  { key: 'weight', label: 'Weight', Icon: FaWeight },
  { key: 'wifi', label: 'Wi-Fi', Icon: FaWifi },
  { key: 'wine-bottle', label: 'Wine bottle', Icon: FaWineBottle },
  { key: 'wrench', label: 'Wrench', Icon: FaWrench },
]

const byKey = new Map<string, CategoryFa5Entry>()
for (const e of CATEGORY_FA5_ICONS) {
  byKey.set(e.key.toLowerCase(), e)
}

export function getCategoryFa5Icon(
  key: string | null | undefined,
): IconType | null {
  const k = key?.trim().toLowerCase()
  if (!k) return null
  return byKey.get(k)?.Icon ?? null
}

export function filterCategoryIcons(query: string): CategoryFa5Entry[] {
  const q = query.trim().toLowerCase().replace(/\s+/g, ' ')
  if (!q) return CATEGORY_FA5_ICONS
  return CATEGORY_FA5_ICONS.filter((e) => {
    if (e.key.includes(q)) return true
    const label = e.label.toLowerCase()
    if (label.includes(q)) return true
    return q.split(' ').every((word) => word && (e.key.includes(word) || label.includes(word)))
  })
}
