import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F1F5F9",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  header: {
    backgroundColor: "#F1F5F9",
    paddingTop: 14,
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  title: {
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "700",
    color: "#0F172A",
    letterSpacing: -0.4,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  /** Room for orange ring + camera badge (same accent as provider profile / edit). */
  avatarWrap: {
    width: 88,
    height: 88,
    position: "relative",
  },
  avatarOuterRing: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#F08E10",
    padding: 4,
    shadowColor: "#F08E10",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 5,
  },
  avatarRingInner: {
    flex: 1,
    borderRadius: 38,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  avatar: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
  },
  avatarPlaceholder: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FDBA74",
    alignItems: "center",
    justifyContent: "center",
  },
  cameraButton: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: "#F08E10",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#F08E10",
    shadowOpacity: 0.35,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0F172A",
    lineHeight: 24,
  },
  username: {
    marginTop: 4,
    fontSize: 12,
    color: "#64748B",
  },
  badgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    flexWrap: "wrap",
  },
  memberBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FFEDD5",
  },
  memberBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#EA580C",
  },
  bullet: {
    color: "#CBD5E1",
    fontSize: 10,
  },
  location: {
    fontSize: 10,
    color: "#64748B",
    fontWeight: "500",
  },
  statsGrid: {
    marginTop: 32,
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingVertical: 12,
    alignItems: "center",
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  statLabel: {
    marginBottom: 4,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: "#94A3B8",
  },
  statValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
  },
  section: {
    paddingHorizontal: 24,
    marginTop: 24,
  },
  bottomSection: {
    marginBottom: 16,
  },
  sectionLabel: {
    marginLeft: 8,
    marginBottom: 12,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: "#94A3B8",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  row: {
    minHeight: 64,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flex: 1,
  },
  rowTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  rowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rowIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  rowTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
  },
  rowSubtitle: {
    marginTop: 2,
    fontSize: 10,
    color: "#94A3B8",
  },
  cardDivider: {
    height: 1,
    marginLeft: 16,
    backgroundColor: "#F8FAFC",
  },
  chevron: {
    marginLeft: 2,
  },
  languagePillGroup: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    borderRadius: 12,
    padding: 4,
  },
  languageActive: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 12,
    shadowColor: "#0F172A",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  languageActiveText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#EA580C",
  },
  languageInactive: {
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  languageInactiveText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#64748B",
  },
  trailingText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748B",
  },
  logoutRow: {
    backgroundColor: "#FFFFFF",
  },
  logoutIcon: {
    backgroundColor: "#FEF2F2",
  },
  logoutTitle: {
    color: "#EF4444",
  },
  destructiveText: {
    color: "#EF4444",
  },
  arabicText: {
    writingDirection: "rtl",
    textAlign: "left",
  },
});
