import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fff" },
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  header: {
    paddingTop: 4,
    paddingBottom: 18,
    paddingHorizontal: 20,
    backgroundColor: "#fff",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E5E7EB",
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  /** Compact row for stack headerRight (notification + avatar). */
  navHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 4,
    gap: 8,
  },
  addressButton: { flexDirection: "row", alignItems: "center" },
  locationIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#eef2ff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  deliveringTo: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#9ca3af",
    textTransform: "uppercase",
  },
  /** Client display name in header (natural casing). */
  headerClientName: {
    fontSize: 12,
    fontWeight: "800",
    color: "#6b7280",
  },
  addressTextContainer: { flexDirection: "row", alignItems: "center" },
  addressText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#111827",
    marginRight: 4,
  },
  headerRight: { flexDirection: "row", alignItems: "center" },
  notificationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#f3f4f6",
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  notificationBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  notificationBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
  },
  avatarContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#eef2ff",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1.5,
    elevation: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  avatar: { width: "100%", height: "100%" },
  searchContainer: { flexDirection: "row", alignItems: "center" },
  homeSearchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingLeft: 6,
    paddingRight: 12,
    paddingVertical: 6,
    minHeight: 54,
    shadowColor: "#4F46E5",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 4,
  },
  homeSearchBarPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  homeSearchIconBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  homeSearchTextBlock: {
    flex: 1,
    justifyContent: "center",
    paddingRight: 4,
  },
  homeSearchPlaceholder: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
    letterSpacing: -0.2,
  },
  homeSearchHint: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: "500",
    color: "#9CA3AF",
  },
  homeSearchChevron: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  },
  searchInputContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f9fafb",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#f3f4f6",
    paddingHorizontal: 14,
    height: 48,
  },
  searchIcon: { marginRight: 8 },
  filterButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#f3f4f6",
    marginLeft: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1.5,
    elevation: 2,
  },
  mainContent: { flex: 1 },
  activeOrderContainer: { paddingHorizontal: 24, paddingTop: 24 },
  activeOrderCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "#f3f4f6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
    position: "relative",
    overflow: "hidden",
  },
  cardPattern: {
    position: "absolute",
    top: -16,
    right: -16,
    width: 96,
    height: 96,
    backgroundColor: "#eef2ff",
    borderRadius: 40,
    transform: [{ rotate: "45deg" }],
  },
  cardContent: { zIndex: 1 },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  cardHeaderLeft: { flexDirection: "row", alignItems: "center" },
  orderIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#4f46e5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    shadowColor: "#4f46e5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  orderId: { fontSize: 14, fontWeight: "bold", color: "#111827" },
  orderStatus: { flexDirection: "row", alignItems: "center" },
  statusIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#4f46e5",
    marginRight: 4,
  },
  statusText: { fontSize: 12, color: "#4f46e5", fontWeight: "500" },
  trackButton: {
    backgroundColor: "#f9fafb",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#f3f4f6",
  },
  trackButtonText: { fontSize: 12, fontWeight: "600", color: "#4b5563" },
  progressBarBackground: {
    width: "100%",
    height: 6,
    backgroundColor: "#f3f4f6",
    borderRadius: 3,
    marginBottom: 12,
    overflow: "hidden",
  },
  progressBarFill: {
    width: "75%",
    height: "100%",
    backgroundColor: "#4f46e5",
    borderRadius: 3,
  },
  orderDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderItems: { fontSize: 12, color: "#6b7280" },
  orderPrice: { fontSize: 12, fontWeight: "600", color: "#111827" },
  categoriesContainer: { paddingHorizontal: 24, marginTop: 24 },
  categoriesHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  categoriesTitle: { fontSize: 18, fontWeight: "bold", color: "#111827" },
  viewAllButton: { fontSize: 12, fontWeight: "600", color: "#4f46e5" },
  categoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  categoryItem: { width: "22%", alignItems: "center", marginBottom: 24 },
  categoryIconContainer: {
    width: 72,
    height: 72,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#f3f4f6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 8,
  },
  categoryName: { fontSize: 12, fontWeight: "500", color: "#4b5563" },
  recommendedContainer: { marginTop: 16 },
  recommendedHeader: { paddingHorizontal: 24, marginBottom: 16 },
  recommendedTitle: { fontSize: 18, fontWeight: "bold", color: "#111827" },
  recommendedSubtitle: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  recommendedScrollView: { paddingLeft: 24, paddingBottom: 24 },
  popularContainer: { paddingHorizontal: 24, marginBottom: 32 },
  popularTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 16,
  },
  popularList: {},
  popularItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#f3f4f6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  popularItemImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
    marginRight: 16,
  },
  popularItemContent: { flex: 1 },
  popularItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  popularItemTitle: { fontSize: 14, fontWeight: "bold", color: "#111827" },
  popularItemInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 4,
  },
  popularItemRating: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#111827",
    marginLeft: 4,
  },
  dot: { color: "#d1d5db", marginHorizontal: 4 },
  popularItemCategory: { fontSize: 12, color: "#6b7280" },
  popularItemDistance: { fontSize: 12, color: "#6b7280" },
  popularItemTags: { flexDirection: "row", alignItems: "center", marginTop: 8 },
  tag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginRight: 8,
  },
  tagText: { fontSize: 10, fontWeight: "500" },
});
