/**
 * Admin UI routes: one folder per screen / domain.
 * Import from `features/admin` or this barrel ? avoid deep paths in App.
 */
export { LoginPage } from './login/LoginPage'
export { DashboardHomePage } from './dashboard/DashboardHomePage'
export { PlaceholderPage } from './placeholder/PlaceholderPage'
export { ServiceCategoriesAdminPage } from './service_category/ServiceCategoriesAdminPage'
export { ServicesAdminPage } from './service/ServicesAdminPage'
export { AccessBlockedPage } from './access_blocked/AccessBlockedPage'
export { LegalDocumentsAdminPage } from './legal_documents/LegalDocumentsAdminPage'
export { UsersAdminPage } from './users/UsersAdminPage'
export { UsersDetailsPage } from './users/UsersDetailsPage'
export { CompaniesAdminPage } from './companies/CompaniesAdminPage'
export { PendingProvidersPage } from './validations/PendingProvidersPage'
export { PendingCompaniesPage } from './validations/PendingCompaniesPage'
export { ValidationHistoryPage } from './validations/ValidationHistoryPage'
export { AdminAppointmentsPage } from './appointments/AdminAppointmentsPage'
export { AdminAppointmentDetailPage } from './appointments/AdminAppointmentDetailPage'
export { AdminComplaintsPage } from './complaints/AdminComplaintsPage'
export { AdminComplaintDetailPage } from './complaints/AdminComplaintDetailPage'
export { AdminReviewsPage } from './reviews/AdminReviewsPage'
export { AdminReviewDetailPage } from './reviews/AdminReviewDetailPage'
export { FaqAdminPage } from './faq/FaqAdminPage'
export { SupportMessagesAdminPage } from './support/SupportMessagesAdminPage'
export { ActivityLogsAdminPage } from './activity_logs/ActivityLogsAdminPage'
