-- Extend company audit log actions for admin activity tracking
ALTER TYPE "CompanyAuditAction" ADD VALUE 'APPOINTMENT_CONFIRMED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'APPOINTMENT_REFUSED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'APPOINTMENT_RESCHEDULED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'APPOINTMENT_ASSIGNED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'COMPLAINT_REVIEWED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'EMPLOYEE_INVITED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'EMPLOYEE_INVITATION_CANCELLED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'EMPLOYEE_REMOVED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'SERVICE_UPDATED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'SERVICE_TOGGLED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'SERVICE_GALLERY_UPDATED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'SCHEDULE_AVAILABILITY_UPDATED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'SCHEDULE_DAY_OFF_CREATED';
ALTER TYPE "CompanyAuditAction" ADD VALUE 'SCHEDULE_DAY_OFF_DELETED';
