export type NotificationType =
  | 'APPOINTMENT_NEW_REQUEST'
  | 'APPOINTMENT_CONFIRMED'
  | 'APPOINTMENT_REFUSED'
  | 'APPOINTMENT_RESCHEDULED'
  | 'APPOINTMENT_RESCHEDULE_ACCEPTED'
  | 'APPOINTMENT_RESCHEDULE_DECLINED'
  | 'APPOINTMENT_CANCELLED_CLIENT'
  | 'APPOINTMENT_CANCELLED_PROVIDER'
  | 'APPOINTMENT_REMINDER_24H'
  | 'APPOINTMENT_REMINDER_1H'
  | 'APPOINTMENT_START_DUE'
  | 'APPOINTMENT_EN_ROUTE'
  | 'APPOINTMENT_STARTED'
  | 'APPOINTMENT_PROVIDER_ENDED'
  | 'APPOINTMENT_COMPLETED'
  | 'ACCOUNT_VERIFIED'
  | 'ACCOUNT_REJECTED'
  | 'DOCUMENT_ACCEPTED'
  | 'DOCUMENT_REJECTED'
  | 'NEW_REVIEW'
  | 'COMPLAINT_FILED'
  | 'COMPLAINT_STATUS_UPDATED'
  | 'COMPLAINT_RESOLVED'
  | 'COMPLAINT_DISMISSED'
  | 'SYSTEM_ANNOUNCEMENT'
  | 'EMPLOYEE_INVITATION_RECEIVED'
  | 'EMPLOYEE_INVITATION_ACCEPTED'
  | 'EMPLOYEE_INVITATION_DECLINED'
  | 'EMPLOYEE_INVITATION_CANCELLED'
  | 'EMPLOYEE_REMOVED_FROM_COMPANY'
  | 'COMPANY_NEW_REQUEST'
  | 'COMPANY_BOOKING_CANCELLED'
  | 'APPOINTMENT_PROVIDER_ASSIGNED'

export type AppNotification = {
  id: string
  type: NotificationType
  title: string
  body: string
  data: Record<string, unknown> | null
  isRead: boolean
  readAt?: string | null
  createdAt: string
}
