-- Reassign any rows still using NEW_MESSAGE (legacy).
UPDATE "notifications"
SET "type" = 'SYSTEM_ANNOUNCEMENT'::"NotificationType"
WHERE "type" = 'NEW_MESSAGE'::"NotificationType";

-- Replace enum without NEW_MESSAGE (PostgreSQL cannot DROP ENUM VALUE in-place).
CREATE TYPE "NotificationType_new" AS ENUM (
  'APPOINTMENT_NEW_REQUEST',
  'APPOINTMENT_CONFIRMED',
  'APPOINTMENT_REFUSED',
  'APPOINTMENT_RESCHEDULED',
  'APPOINTMENT_RESCHEDULE_ACCEPTED',
  'APPOINTMENT_RESCHEDULE_DECLINED',
  'APPOINTMENT_CANCELLED_CLIENT',
  'APPOINTMENT_CANCELLED_PROVIDER',
  'APPOINTMENT_REMINDER_24H',
  'APPOINTMENT_REMINDER_1H',
  'APPOINTMENT_EN_ROUTE',
  'APPOINTMENT_STARTED',
  'APPOINTMENT_PROVIDER_ENDED',
  'APPOINTMENT_COMPLETED',
  'ACCOUNT_VERIFIED',
  'ACCOUNT_REJECTED',
  'DOCUMENT_ACCEPTED',
  'DOCUMENT_REJECTED',
  'NEW_REVIEW',
  'SYSTEM_ANNOUNCEMENT'
);

ALTER TABLE "notifications"
  ALTER COLUMN "type" TYPE "NotificationType_new"
  USING ("type"::text::"NotificationType_new");

DROP TYPE "NotificationType";

ALTER TYPE "NotificationType_new" RENAME TO "NotificationType";
