import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F3F4F6",
  },
  screenWrap: {
    flex: 1,
    maxWidth: 420,
    alignSelf: "center",
    width: "100%",
    backgroundColor: "#F9FAFB",
  },
  header: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 24,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  circleButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  },
  cartDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#EF4444",
    borderWidth: 1,
    borderColor: "#FFFFFF",
    position: "absolute",
    right: 11,
    top: 10,
  },
  headerTitle: {
    flex: 1,
    marginHorizontal: 12,
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
    textAlign: "center",
  },
  filterRow: {
    gap: 8,
    paddingBottom: 6,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  chipPrimary: {
    borderColor: "#4F46E5",
    backgroundColor: "#4F46E5",
  },
  chipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4B5563",
  },
  chipPrimaryText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
    gap: 14,
  },
  centerWrap: {
    paddingVertical: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  errorText: {
    color: "#b91c1c",
    textAlign: "center",
    fontSize: 14,
  },
  subCategoriesRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  subItem: {
    width: "24%",
    alignItems: "center",
    gap: 8,
  },
  subIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  subIconWrapActive: {
    backgroundColor: "#EEF2FF",
    borderColor: "#E0E7FF",
  },
  subText: {
    fontSize: 10,
    lineHeight: 12,
    textAlign: "center",
    color: "#4B5563",
    fontWeight: "600",
  },
  listHeader: {
    marginTop: 6,
    marginBottom: 2,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  listTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
  },
  resultText: {
    fontSize: 12,
    color: "#6B7280",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    padding: 14,
    position: "relative",
  },
  topBadge: {
    position: "absolute",
    right: 0,
    top: 0,
    backgroundColor: "#ECFDF5",
    borderBottomLeftRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  topBadgeText: {
    fontSize: 10,
    color: "#047857",
    fontWeight: "800",
  },
  cardMainRow: {
    flexDirection: "row",
    gap: 12,
  },
  cardImageWrap: {
    width: 96,
    height: 96,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#F3F4F6",
  },
  cardImage: {
    width: "100%",
    height: "100%",
  },
  demandOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingVertical: 3,
    alignItems: "center",
  },
  demandText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "700",
  },
  cardInfo: {
    flex: 1,
    justifyContent: "space-between",
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 4,
  },
  cardDescription: {
    fontSize: 12,
    color: "#6B7280",
    lineHeight: 16,
  },
  priceRow: {
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  durationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  durationText: {
    fontSize: 10,
    color: "#6B7280",
  },
  priceTextRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  priceText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#4F46E5",
  },
  unitText: {
    fontSize: 10,
    color: "#9CA3AF",
    marginBottom: 2,
  },
  addButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  cardFooter: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#F9FAFB",
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  rating: {
    fontSize: 10,
    color: "#111827",
    fontWeight: "800",
  },
  reviews: {
    fontSize: 10,
    color: "#9CA3AF",
  },
  metaText: {
    marginLeft: 12,
    fontSize: 10,
    color: "#6B7280",
    fontWeight: "600",
  },
  vatText: {
    marginLeft: "auto",
    fontSize: 10,
    color: "#9CA3AF",
  },
  promoBanner: {
    borderRadius: 18,
    marginTop: 6,
    backgroundColor: "#312E81",
    minHeight: 96,
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  offerLabel: {
    fontSize: 10,
    color: "#C7D2FE",
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  offerTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "800",
    marginTop: 2,
  },
  offerSubtitle: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 10,
  },
  claimButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  claimButtonText: {
    fontSize: 12,
    color: "#1F2937",
    fontWeight: "800",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.2)",
    justifyContent: "flex-end",
  },
  sheet: {
    height: "85%",
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
  },
  sheetImageWrap: {
    height: 190,
    position: "relative",
  },
  sheetImage: {
    width: "100%",
    height: "100%",
  },
  closeButton: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetTitleWrap: {
    position: "absolute",
    left: 20,
    bottom: 16,
    right: 56,
  },
  sheetTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 4,
  },
  sheetSubtitle: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 12,
    fontWeight: "600",
  },
  sheetBody: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  sheetDesc: {
    color: "#4B5563",
    fontSize: 14,
    lineHeight: 20,
  },
  readMore: {
    color: "#4F46E5",
    marginTop: 8,
    fontSize: 12,
    fontWeight: "700",
  },
  sectionTitle: {
    marginTop: 18,
    marginBottom: 10,
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  durationWrap: {
    gap: 10,
    paddingBottom: 6,
  },
  durationCard: {
    width: 82,
    height: 102,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  durationCardSelected: {
    borderColor: "#4F46E5",
    backgroundColor: "#EEF2FF",
  },
  recommended: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    textAlign: "center",
    backgroundColor: "#4F46E5",
    color: "#FFFFFF",
    fontSize: 8,
    fontWeight: "800",
    paddingVertical: 2,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  durationHours: {
    fontSize: 24,
    color: "#111827",
    fontWeight: "800",
    marginTop: 8,
  },
  durationHoursSelected: {
    color: "#4338CA",
  },
  durationLabel: {
    fontSize: 12,
    color: "#6B7280",
  },
  durationLabelSelected: {
    color: "#4F46E5",
  },
  counterCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    backgroundColor: "#F9FAFB",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  counterTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  counterSubtitle: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  counterActions: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    padding: 4,
    gap: 6,
  },
  counterBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  counterBtnAdd: {
    backgroundColor: "#EEF2FF",
  },
  counterValue: {
    width: 18,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
  },
  addonRow: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    backgroundColor: "#FFFFFF",
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  addonTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  addonSubtitle: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  addonPrice: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  textArea: {
    minHeight: 90,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#F3F4F6",
    borderRadius: 16,
    padding: 14,
    textAlignVertical: "top",
    color: "#111827",
  },
  sheetSpacer: {
    height: 120,
  },
  footerBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
  },
  totalWrap: {
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  totalLabel: {
    fontSize: 12,
    color: "#6B7280",
  },
  totalValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
  },
  totalMeta: {
    fontSize: 12,
    color: "#4F46E5",
    fontWeight: "600",
  },
  bookButton: {
    height: 52,
    borderRadius: 12,
    backgroundColor: "#4F46E5",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  bookText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 15,
  },
});
