import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F3F4F6",
  },
  screenWrap: {
    flex: 1,
    maxWidth: 420,
    alignSelf: "center",
    width: "100%",
    backgroundColor: "#F9FAFB",
  },
  header: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 24,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  circleButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  },
  cartDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#EF4444",
    borderWidth: 1,
    borderColor: "#FFFFFF",
    position: "absolute",
    right: 11,
    top: 10,
  },
  headerTitle: {
    flex: 1,
    marginHorizontal: 12,
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
    textAlign: "center",
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
    gap: 14,
  },
  centerWrap: {
    paddingVertical: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  errorText: {
    color: "#b91c1c",
    textAlign: "center",
    fontSize: 14,
  },
  subCategoriesRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  subItem: {
    width: "24%",
    alignItems: "center",
    gap: 8,
  },
  subIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  subIconWrapActive: {
    backgroundColor: "#EEF2FF",
    borderColor: "#E0E7FF",
  },
  subText: {
    fontSize: 10,
    lineHeight: 12,
    textAlign: "center",
    color: "#4B5563",
    fontWeight: "600",
  },
  listHeader: {
    marginTop: 6,
    marginBottom: 2,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  listTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
  },
  resultText: {
    fontSize: 12,
    color: "#6B7280",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    padding: 14,
  },
  cardMainRow: {
    flexDirection: "row",
    gap: 12,
  },
  cardImageWrap: {
    width: 96,
    height: 96,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#F3F4F6",
  },
  cardImage: {
    width: "100%",
    height: "100%",
  },
  cardInfo: {
    flex: 1,
    justifyContent: "space-between",
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 4,
  },
  cardDescription: {
    fontSize: 12,
    color: "#6B7280",
    lineHeight: 16,
  },
  priceRow: {
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  durationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  durationText: {
    fontSize: 10,
    color: "#6B7280",
  },
  cardProviderCountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  cardProviderCountText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#4F46E5",
  },
  priceTextRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  priceText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#4F46E5",
  },
  unitText: {
    fontSize: 10,
    color: "#9CA3AF",
    marginBottom: 2,
  },
  addButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  promoBanner: {
    borderRadius: 18,
    marginTop: 6,
    backgroundColor: "#312E81",
    minHeight: 96,
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  offerLabel: {
    fontSize: 10,
    color: "#C7D2FE",
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  offerTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "800",
    marginTop: 2,
  },
  offerSubtitle: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 10,
  },
  claimButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  claimButtonText: {
    fontSize: 12,
    color: "#1F2937",
    fontWeight: "800",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.2)",
    justifyContent: "flex-end",
  },
  sheet: {
    height: "85%",
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
  },
  sheetImageWrap: {
    height: 190,
    position: "relative",
  },
  sheetImage: {
    width: "100%",
    height: "100%",
  },
  closeButton: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetTitleBlock: {
    marginBottom: 14,
  },
  sheetTitle: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 4,
  },
  sheetSubtitle: {
    color: "#6B7280",
    fontSize: 12,
    fontWeight: "600",
  },
  sheetBody: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  sheetDesc: {
    color: "#4B5563",
    fontSize: 14,
    lineHeight: 20,
  },
  readMore: {
    color: "#4F46E5",
    marginTop: 8,
    fontSize: 12,
    fontWeight: "700",
  },
  sectionTitle: {
    marginTop: 18,
    marginBottom: 10,
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  counterCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    backgroundColor: "#F9FAFB",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  counterTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  counterSubtitle: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  providersCountValue: {
    fontSize: 28,
    fontWeight: "800",
    color: "#4F46E5",
    minWidth: 40,
    textAlign: "right",
  },
  sheetSpacer: {
    height: 100,
  },
  footerBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
  },
  bookButton: {
    height: 52,
    borderRadius: 12,
    backgroundColor: "#4F46E5",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    width: "100%",
  },
  bookText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 15,
  },
});
